CREATE TABLE problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform VARCHAR(50) NOT NULL,
    number VARCHAR(100) NOT NULL,
    link VARCHAR(1000) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    memo VARCHAR(2000) NOT NULL,
    result VARCHAR(20),
    needs_review BOOLEAN NOT NULL,
    reviewed_at DATE,
    created_at TIMESTAMP NOT NULL,
    last_solved_at DATE,
    bookmarked BOOLEAN NOT NULL,
    CONSTRAINT chk_problem_difficulty CHECK (difficulty IN ('easy', 'medium', 'hard')),
    CONSTRAINT chk_problem_result CHECK (result IS NULL OR result IN ('success', 'fail', 'partial'))
);

CREATE TABLE problem_tags (
    problem_id BIGINT NOT NULL,
    tag VARCHAR(100) NOT NULL,
    PRIMARY KEY (problem_id, tag),
    CONSTRAINT fk_problem_tags_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE
);

CREATE TABLE problem_review_history (
    problem_id BIGINT NOT NULL,
    reviewed_date DATE NOT NULL,
    PRIMARY KEY (problem_id, reviewed_date),
    CONSTRAINT fk_problem_review_history_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE
);

CREATE TABLE problem_solved_dates (
    problem_id BIGINT NOT NULL,
    solved_date DATE NOT NULL,
    PRIMARY KEY (problem_id, solved_date),
    CONSTRAINT fk_problem_solved_dates_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL UNIQUE,
    review_count INTEGER NOT NULL,
    last_reviewed_date DATE NOT NULL,
    next_review_date DATE NOT NULL,
    CONSTRAINT fk_reviews_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE
);

CREATE TABLE study_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE study_set_problem_ids (
    study_set_id BIGINT NOT NULL,
    problem_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (study_set_id, problem_id),
    CONSTRAINT fk_study_set_problem_ids_study_set FOREIGN KEY (study_set_id) REFERENCES study_sets(id) ON DELETE CASCADE
);

CREATE TABLE study_set_completed_problem_ids (
    study_set_id BIGINT NOT NULL,
    problem_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (study_set_id, problem_id),
    CONSTRAINT fk_study_set_completed_problem_ids_study_set FOREIGN KEY (study_set_id) REFERENCES study_sets(id) ON DELETE CASCADE
);

CREATE INDEX idx_reviews_next_review_date ON reviews(next_review_date);
