CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    platform VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    number VARCHAR(100) NOT NULL,
    link VARCHAR(1000) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    memo VARCHAR(2000) NOT NULL,
    result VARCHAR(20),
    needs_review BOOLEAN NOT NULL,
    reviewed_at DATE,
    created_at TIMESTAMP NOT NULL,
    last_solved_at DATE,
    bookmarked BOOLEAN NOT NULL,
    CONSTRAINT fk_problems_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_problem_difficulty CHECK (difficulty IN ('easy', 'medium', 'hard')),
    CONSTRAINT chk_problem_result CHECK (result IS NULL OR result IN ('success', 'fail', 'partial'))
);

CREATE TABLE problem_tags (
    problem_id BIGINT NOT NULL,
    tag VARCHAR(100) NOT NULL,
    PRIMARY KEY (problem_id, tag),
    CONSTRAINT fk_problem_tags_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE
);

CREATE TABLE problem_review_history (
    problem_id BIGINT NOT NULL,
    reviewed_date DATE NOT NULL,
    PRIMARY KEY (problem_id, reviewed_date),
    CONSTRAINT fk_problem_review_history_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE
);

CREATE TABLE problem_solved_dates (
    problem_id BIGINT NOT NULL,
    solved_date DATE NOT NULL,
    PRIMARY KEY (problem_id, solved_date),
    CONSTRAINT fk_problem_solved_dates_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL UNIQUE,
    review_count INTEGER NOT NULL,
    last_reviewed_date DATE NOT NULL,
    next_review_date DATE NOT NULL,
    CONSTRAINT fk_reviews_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE
);

CREATE TABLE review_history_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    review_count_after_check INTEGER NOT NULL,
    interval_days INTEGER NOT NULL,
    reviewed_at DATE NOT NULL,
    next_review_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_review_history_entries_review FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_history_entries_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_history_entries_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE study_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_study_sets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE study_set_problem_ids (
    study_set_id BIGINT NOT NULL,
    problem_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (study_set_id, problem_id),
    CONSTRAINT fk_study_set_problem_ids_study_set FOREIGN KEY (study_set_id) REFERENCES study_sets(id) ON DELETE CASCADE
);

CREATE TABLE study_set_completed_problem_ids (
    study_set_id BIGINT NOT NULL,
    problem_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (study_set_id, problem_id),
    CONSTRAINT fk_study_set_completed_problem_ids_study_set FOREIGN KEY (study_set_id) REFERENCES study_sets(id) ON DELETE CASCADE
);

CREATE TABLE user_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_token VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    last_accessed_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE external_problem_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(50) NOT NULL,
    query_key VARCHAR(500) NOT NULL,
    query_hash VARCHAR(500) NOT NULL,
    content_json TEXT NOT NULL,
    total_elements BIGINT NOT NULL,
    total_pages INTEGER NOT NULL,
    fetched_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_external_problem_cache_provider_hash UNIQUE (provider, query_hash)
);

CREATE TABLE programmers_problem_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(100) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    problem_number VARCHAR(100) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    tags_json TEXT NOT NULL,
    external_url VARCHAR(1000) NOT NULL,
    recommendation_reason VARCHAR(1000) NOT NULL,
    source_updated_at TIMESTAMP NOT NULL,
    ingested_at TIMESTAMP NOT NULL
);

CREATE TABLE search_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    query VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_search_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE problem_interaction_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    problem_ref VARCHAR(100) NOT NULL,
    source VARCHAR(20) NOT NULL,
    platform VARCHAR(50) NOT NULL,
    problem_number VARCHAR(100) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    source_query VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_problem_interaction_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_problem_interaction_events_source CHECK (source IN ('INTERNAL', 'EXTERNAL')),
    CONSTRAINT chk_problem_interaction_events_difficulty CHECK (difficulty IN ('easy', 'medium', 'hard')),
    CONSTRAINT chk_problem_interaction_events_type CHECK (
        event_type IN ('SEARCH_CLICK', 'DETAIL_VIEW', 'BOOKMARK', 'MARK_REVIEW')
    )
);

CREATE TABLE problem_interaction_event_tags (
    event_id BIGINT NOT NULL,
    tag VARCHAR(100) NOT NULL,
    PRIMARY KEY (event_id, tag),
    CONSTRAINT fk_problem_interaction_event_tags_event
        FOREIGN KEY (event_id) REFERENCES problem_interaction_events(id) ON DELETE CASCADE
);

CREATE INDEX idx_problems_user_id ON problems(user_id);
CREATE INDEX idx_study_sets_user_id ON study_sets(user_id);
CREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX idx_user_sessions_expires_at ON user_sessions(expires_at);
CREATE INDEX idx_external_problem_cache_expires_at ON external_problem_cache(expires_at);
CREATE INDEX idx_programmers_problem_catalog_problem_number ON programmers_problem_catalog(problem_number);
CREATE INDEX idx_review_history_entries_user_reviewed_at ON review_history_entries(user_id, reviewed_at DESC);
CREATE INDEX idx_review_history_entries_problem_reviewed_at ON review_history_entries(problem_id, reviewed_at DESC);
CREATE INDEX idx_search_events_user_created_at ON search_events(user_id, created_at DESC);
CREATE INDEX idx_problem_interaction_events_user_created_at
    ON problem_interaction_events(user_id, created_at DESC);
