CREATE TABLE external_problem_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(50) NOT NULL,
    query_key VARCHAR(500) NOT NULL,
    query_hash VARCHAR(500) NOT NULL,
    content_json TEXT NOT NULL,
    total_elements BIGINT NOT NULL,
    total_pages INTEGER NOT NULL,
    fetched_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_external_problem_cache_provider_hash UNIQUE (provider, query_hash)
);

CREATE INDEX idx_external_problem_cache_expires_at ON external_problem_cache(expires_at);
CREATE INDEX idx_external_problem_cache_provider ON external_problem_cache(provider);
