CREATE TABLE programmers_problem_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(100) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    problem_number VARCHAR(100) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    tags_json TEXT NOT NULL,
    external_url VARCHAR(1000) NOT NULL,
    recommendation_reason VARCHAR(1000) NOT NULL,
    source_updated_at TIMESTAMP NOT NULL,
    ingested_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_programmers_problem_catalog_problem_number ON programmers_problem_catalog(problem_number);
CREATE INDEX idx_programmers_problem_catalog_source_updated_at ON programmers_problem_catalog(source_updated_at DESC);
