CREATE TABLE problem_solve_attempt_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    result VARCHAR(20),
    memo VARCHAR(2000) NOT NULL,
    solved_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_problem_solve_attempt_entries_problem
        FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE,
    CONSTRAINT fk_problem_solve_attempt_entries_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_problem_solve_attempt_entries_result
        CHECK (result IS NULL OR result IN ('success', 'fail', 'partial'))
);

CREATE INDEX idx_problem_solve_attempt_entries_problem_solved_at
    ON problem_solve_attempt_entries(problem_id, solved_at DESC);
