CREATE TABLE review_history_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    review_count_after_check INTEGER NOT NULL,
    interval_days INTEGER NOT NULL,
    reviewed_at DATE NOT NULL,
    next_review_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_review_history_entries_review FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_history_entries_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_history_entries_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_review_history_entries_review_count_non_negative CHECK (review_count_after_check >= 0),
    CONSTRAINT chk_review_history_entries_interval_positive CHECK (interval_days > 0)
);

CREATE INDEX idx_review_history_entries_user_reviewed_at ON review_history_entries(user_id, reviewed_at DESC);
CREATE INDEX idx_review_history_entries_problem_reviewed_at ON review_history_entries(problem_id, reviewed_at DESC);
