CREATE TABLE search_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    query VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_search_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_search_events_user_created_at ON search_events(user_id, created_at DESC);

CREATE TABLE problem_interaction_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    problem_ref VARCHAR(100) NOT NULL,
    source VARCHAR(20) NOT NULL,
    platform VARCHAR(50) NOT NULL,
    problem_number VARCHAR(100) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    source_query VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_problem_interaction_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_problem_interaction_events_source CHECK (source IN ('INTERNAL', 'EXTERNAL')),
    CONSTRAINT chk_problem_interaction_events_difficulty CHECK (difficulty IN ('easy', 'medium', 'hard')),
    CONSTRAINT chk_problem_interaction_events_type CHECK (
        event_type IN ('SEARCH_CLICK', 'DETAIL_VIEW', 'BOOKMARK', 'MARK_REVIEW')
    )
);

CREATE TABLE problem_interaction_event_tags (
    event_id BIGINT NOT NULL,
    tag VARCHAR(100) NOT NULL,
    PRIMARY KEY (event_id, tag),
    CONSTRAINT fk_problem_interaction_event_tags_event
        FOREIGN KEY (event_id) REFERENCES problem_interaction_events(id) ON DELETE CASCADE
);

CREATE INDEX idx_problem_interaction_events_user_created_at
    ON problem_interaction_events(user_id, created_at DESC);
